export const CATEGORIES = [
  {
    id: 'llantas',
    catalogName: 'Llantas',
    name: 'Llantas',
    nameEn: 'Tires',
    description: 'Llantas para moto, scooter y mototaxi según medida, uso y tipo de terreno.',
    descriptionEn: 'Tires for motorcycles, scooters and mototaxis by size, use and terrain type.',
    cta: 'Ver catálogo de llantas',
    ctaEn: 'Browse tire catalog',
    waMessage: 'Hola, quiero cotizar llantas para mi moto. Mi medida o modelo es: ',
    waMessageEn: 'Hi, I want to quote tires for my motorcycle. My size or model is: ',
    enabled: true,
    comingSoon: false,
  },
  {
    id: 'camaras',
    catalogName: 'Cámaras',
    name: 'Cámaras',
    nameEn: 'Tubes',
    description: 'Cámaras para moto en diferentes medidas, ideales para reposición rápida y segura.',
    descriptionEn: 'Motorcycle tubes in various sizes, ideal for quick and safe replacement.',
    cta: 'Ver catálogo de cámaras',
    ctaEn: 'Browse tube catalog',
    waMessage: 'Hola, quiero cotizar cámaras para mi moto. Mi medida es: ',
    waMessageEn: 'Hi, I want to quote tubes for my motorcycle. My size is: ',
    enabled: true,
    comingSoon: false,
  },
  {
    id: 'repuestos',
    catalogName: 'Repuestos',
    name: 'Repuestos',
    nameEn: 'Spare Parts',
    description: 'Repuestos seleccionados para mantenimiento, reparación y funcionamiento de tu moto.',
    descriptionEn: 'Curated spare parts for motorcycle maintenance, repair and operation.',
    cta: 'Ver catálogo de repuestos',
    ctaEn: 'Browse spare parts catalog',
    waMessage: 'Hola, quiero cotizar repuestos para mi moto. Mi modelo y la pieza que necesito es: ',
    waMessageEn: 'Hi, I want to quote spare parts for my motorcycle. My model and part needed is: ',
    enabled: false,
    comingSoon: true,
  },
  {
    id: 'accesorios',
    catalogName: 'Accesorios',
    name: 'Accesorios',
    nameEn: 'Accessories',
    description: 'Productos complementarios para el cuidado, seguridad y mantenimiento de tu moto.',
    descriptionEn: 'Complementary products for motorcycle care, safety and maintenance.',
    cta: 'Ver accesorios',
    ctaEn: 'Browse accessories',
    waMessage: 'Hola, quiero cotizar accesorios para mi moto. Mi modelo es: ',
    waMessageEn: 'Hi, I want to quote accessories for my motorcycle. My model is: ',
    enabled: false,
    comingSoon: true,
  },
]

export function getCategoryById(id) {
  return CATEGORIES.find(cat => cat.id === id)
}
